language: ruby
cache: bundler
#bundler_args: --without development debug
sudo: required
rvm:
  - 2.1.5
before_install:
  - export PATH="$PATH:$(pwd)/fits"
services:
  - redis-server
before_install:
  - sudo apt-get update
  - sudo apt-get install libclamav-dev clamav-freshclam
  - sudo freshclam
before_script:
  - redis-cli info
  - bundle exec rake jetty:start
  - sleep 60
  - bundle exec rake db:setup
after_script:
  - bundle exec rake jetty:stop
notifications:
  email:
    recipients:
      - "peter.binkley@ualberta.ca"
    on_success: "change"
    on_failure: "always"
