development:
  archivist:
    - archivist1@example.com
    - dittest@ualberta.ca
  admin_policy_object_editor:
    - dittest@ualberta.ca
  admin:
    - dittest@ualberta.ca
test:
  archivist:
    - archivist1@example.com
    - archivist2@example.com
    - leland_himself@example.com
  admin_policy_object_editor:
    - archivist1@example.com
  donor:
    - donor1@example.com
    - leland_himself@example.com
  researcher:
    - archivist1@example.com
    - researcher1@example.com
  patron:
    - patron1@example.com
    - leland_himself@example.com
